// This file is used by Code Analysis to maintain SuppressMessage attributes that are applied to this
// project. Project-level suppressions either have no target or are given a specific target and
// scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:Specifications.Core.Interfaces.ISpecification`1.And(Specifications.Core.Interfaces.ISpecification`1)~Specifications.Core.Interfaces.ISpecification`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:Specifications.Core.Interfaces.ISpecification`1.And(System.Linq.Expressions.Expression{System.Func{`0,System.Boolean}})~Specifications.Core.Interfaces.ISpecification`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:Specifications.Core.Interfaces.ISpecification`1.Not~Specifications.Core.Interfaces.ISpecification`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:Specifications.Core.Interfaces.ISpecification`1.Or(Specifications.Core.Interfaces.ISpecification`1)~Specifications.Core.Interfaces.ISpecification`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:Specifications.Core.Interfaces.ISpecification`1.Or(System.Linq.Expressions.Expression{System.Func{`0,System.Boolean}})~Specifications.Core.Interfaces.ISpecification`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:Specifications.Core.Interfaces.ISpecification`1.OrderBy``1(System.Linq.Expressions.Expression{System.Func{`0,``0}})~Specifications.Core.Interfaces.ISpecification`1")]